services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: example_db
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d/

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

volumes:
  mysql: